server:
  port: 10510
spring:
  application:
    name: qiniu-project
  #配置图片大小限制
  servlet:
    multipart:
      max-file-size: "1000MB"
      max-request-size: "10000MB"
# 七牛云配置
qiniu:
  access-key: XBXenHfURaBC2GKPsB724AuR8W36vE27FOa6VRbg
  secret-key: 9OkOoWs3Q2DPmoyphWZNGHQSJdwvMdgXV0j8BZ62
  bucket: wgb
  zone: zone0
  #domain-of-bucket: qkamygyw0.hd-bkt.clouddn.com
  prefix: qlxw7iho1.hd-bkt.clouddn.com
  expire-in-seconds: -1
  # [{'zone0':'华东'}, {'zone1':'华北'},{'zone2':'华南'},{'zoneNa0':'北美'},{'zoneAs0':''}]
  # 链接过期时间，单位是秒，3600代表1小时，-1代表永不过期